# Generated by Django 5.0.2 on 2024-02-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_status_alter_booking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='special_requests',
            field=models.CharField(default='', max_length=500),
        ),
    ]
